title: Knife Talk
description: The podcast for knife nerds hosted by x x x

url: 
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Sponsorship
   url: /contact
 - title: Contact
   url: /contact


social:
   
   twitter: knifetalkpodcast
   facebook: knifetalkpodcast
   email: info@knifetalk.net

google_analytics: "UA-58263416-1"
