title: Knife Talk
description: The podcast for knife nerds hosted by x x x

url: 
baseurl: ""
paginate_path: "episode/page:num/"
permalink: episode/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Hosts
   url: /hosts
 - title: Sponsorship
   url: /sponsorship
 - title: Contact
   url: /contact


social:
   
   twitter: knifetalkpodcast
   facebook: knifetalkpodcast
   email: info@knifetalk.net

google_analytics: "UA-"



# Note that when viewing locally (bundle exec jekyll serve) the baseurl should be "". To build for GitHub pages it should be "/".